# Generated by Django 5.2.12 on 2026-04-29 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table="tbl_product",
        ),
    ]
